# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      .*\.xml|
      tests/.*/.*\.md
    )$

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.12
    hooks:
    - id: ruff-format
    - id: ruff

  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      args: [--config-file=pyproject.toml, --pretty, ./aiida_project]
      pass_filenames: false
      language: python
      types: [python]
