# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      .*\.xml|
      tests/.*/.*\.md
    )$

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    - id: pyupgrade
      args: [--py37-plus]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.252
    hooks:
    - id: ruff

  # NOTE: mypy needs to be installed in the same environment as the package
  # and all of its 3rd party dependencies.
  # See https://jaredkhan.com/blog/mypy-pre-commit for detailed rationale.
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      args: [--config-file=pyproject.toml, --pretty, ./aiida_project]
      # Always analyze all files, since changes in one file can introduce errors
      # in modules that depend on it.
      pass_filenames: false
      require_serial: true
      language: python
      types: [python]
